# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151213153331 on 2016-01-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestFolderPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
    ]
